# Generated by Django 4.2.11 on 2025-05-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=100)),
                ('total_room', models.PositiveIntegerField()),
                ('number_of_students', models.PositiveIntegerField()),
                ('admitted_students', models.PositiveIntegerField()),
                ('vacant_seats', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='hall_images/')),
            ],
        ),
    ]
