# Generated by Django 4.2.11 on 2025-05-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall',
            old_name='number_of_students',
            new_name='total_number_of_students',
        ),
    ]
