# Generated by Django 4.2.11 on 2025-05-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_number_of_students_hall_total_number_of_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall',
            old_name='total_number_of_students',
            new_name='total_number_of_seat',
        ),
    ]
