<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-05-22 09:08
=======
# Generated by Django 5.2.1 on 2025-05-30 04:04
>>>>>>> 72366e15 (WIP: add initial migrations and updates)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('event_description', models.TextField()),
                ('event_date_time', models.DateTimeField()),
                ('event_location', models.TextField()),
                ('event_file', models.JSONField(blank=True, default=list, null=True)),
                ('event_publicist_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='registration.provostbody')),
            ],
        ),
        migrations.CreateModel(
            name='AddFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='events/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='events.event')),
            ],
        ),
    ]
