# Generated by Django 5.2.1 on 2025-06-03 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('registration', '0003_alter_addoffice_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Create_Event',
        ),
    ]
