<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-05-22 09:08
=======
# Generated by Django 5.2.1 on 2025-05-30 03:58
>>>>>>> 72366e15 (WIP: add initial migrations and updates)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('hall_id', models.AutoField(primary_key=True, serialize=False)),
                ('hall_name', models.CharField(max_length=100)),
                ('total_room', models.PositiveIntegerField()),
                ('total_number_of_seat', models.PositiveIntegerField()),
                ('admitted_students', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='hall_images/')),
                ('room_list', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Dining_Shop_Canteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Official Email')),
                ('name', models.CharField(max_length=100)),
                ('official_role', models.CharField(choices=[('assistant_register', 'Assistant Register'), ('administrative_officer', 'Administrative Officer'), ('accountant', 'Accountant'), ('cleaner', 'Cleaner'), ('electrician', 'Electrician'), ('plumber', 'Plumber'), ('gardener', 'Gardener'), ('office_assistant', 'Office Assistant'), ('office_attendant', 'Office Attendant'), ('guard', 'Guard'), ('senior_assistant', 'Senior Assistant'), ('dining', 'Dining'), ('shop', 'Shop'), ('canteen', 'Canteen'), ('others', 'Others')], default='Electrician', max_length=100)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('registration_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('blood_group', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('department_name', models.CharField(max_length=100)),
                ('study_program', models.CharField(choices=[('undergraduate', 'UnderGraduate'), ('graduate', 'Graduate')], max_length=20)),
                ('session', models.CharField(choices=[('2019', '2019-2020'), ('2020', '2020-2021'), ('2021', '2021-2022'), ('2023', '2023-2024'), ('2024', '2024-2025')], max_length=10)),
                ('semester', models.CharField(choices=[('1/1', '1/1'), ('1/2', '1/2'), ('2/1', '2/1'), ('2/2', '2/2'), ('3/1', '3/1'), ('3/2', '3/2'), ('4/1', '4/1'), ('4/2', '4/2'), ('m/1', 'M/1'), ('m/2', 'M/2'), ('m/3', 'M/3')], max_length=20)),
                ('permanent_address', models.TextField()),
                ('home_distance_from_SUST_in_km', models.FloatField()),
                ('family_monthly_income', models.PositiveIntegerField()),
                ('special_reason_for_hall_seat', models.TextField(blank=True, null=True)),
                ('total_credits_offered', models.FloatField()),
                ('total_credits_completed', models.FloatField()),
                ('cgpa', models.FloatField()),
                ('last_semester_gpa', models.FloatField()),
                ('is_resident', models.BooleanField()),
                ('resident_months_in_university_hall', models.PositiveIntegerField(blank=True, null=True)),
                ('convicted', models.BooleanField(help_text='Have ever been penalized by university authority?')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='student_profile_pictures/')),
                ('attached_hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.hall')),
            ],
        ),
        migrations.CreateModel(
            name='AddOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=10)),
                ('user_role', models.CharField(choices=[('student', 'Student'), ('provost_body', 'Provost Body'), ('official_person', 'Official Person'), ('dining_shop_canteen', 'Dining/Shop/Canteen')], max_length=100)),
                ('provost_body_role', models.CharField(blank=True, choices=[('provost', 'Provost'), ('assistant_provost', 'Assistant Provost')], help_text='Only for Provost Body', max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('department_role', models.CharField(blank=True, choices=[('professor', 'Professor'), ('associate_professor', 'Associate Professor'), ('assistant_professor', 'Assistant Professor'), ('lecturer', 'Lecturer')], help_text='Only for Provost Body', max_length=100, null=True)),
                ('official_role', models.CharField(blank=True, choices=[('assistant_register', 'Assistant Register'), ('administrative_officer', 'Administrative Officer'), ('accountant', 'Accountant'), ('cleaner', 'Cleaner'), ('electrician', 'Electrician'), ('plumber', 'Plumber'), ('gardener', 'Gardener'), ('office_assistant', 'Office Assistant'), ('office_attendant', 'Office Attendant'), ('guard', 'Guard'), ('senior_assistant', 'Senior Assistant'), ('dining', 'Dining'), ('shop', 'Shop'), ('canteen', 'Canteen'), ('others', 'Others')], default='Assistant Register', help_text='Only for Official Person', max_length=100, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='student_profile_pictures/')),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.hall')),
            ],
        ),
        migrations.CreateModel(
            name='OfficialPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('official_role', models.CharField(choices=[('assistant_register', 'Assistant Register'), ('administrative_officer', 'Administrative Officer'), ('accountant', 'Accountant'), ('cleaner', 'Cleaner'), ('electrician', 'Electrician'), ('plumber', 'Plumber'), ('gardener', 'Gardener'), ('office_assistant', 'Office Assistant'), ('office_attendant', 'Office Attendant'), ('guard', 'Guard'), ('senior_assistant', 'Senior Assistant'), ('dining', 'Dining'), ('shop', 'Shop'), ('canteen', 'Canteen'), ('others', 'Others')], default='Electrician', max_length=100)),
                ('hall', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='registration.hall')),
            ],
        ),
        migrations.CreateModel(
            name='ProvostBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Official Email')),
                ('name', models.CharField(max_length=100)),
                ('provost_body_role', models.CharField(choices=[('provost', 'Provost'), ('assistant_provost', 'Assistant Provost')], default='provost', max_length=100)),
                ('department', models.CharField(default='', max_length=100)),
                ('department_role', models.CharField(choices=[('professor', 'Professor'), ('associate_professor', 'Associate Professor'), ('assistant_professor', 'Assistant Professor'), ('lecturer', 'Lecturer')], default='Professor', max_length=100)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=10)),
                ('capacity', models.PositiveIntegerField()),
                ('admitted_students', models.PositiveIntegerField(default=0)),
                ('student_list', models.JSONField(blank=True, default=list)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='registration.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(default='', max_length=100)),
                ('department', models.CharField(default='', max_length=100)),
                ('semester', models.CharField(max_length=20)),
                ('session', models.CharField(max_length=10)),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.hall')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.room')),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('user_role', models.CharField(choices=[('student', 'Student'), ('provost_body', 'Provost Body'), ('official_person', 'Official Person'), ('dining_shop_canteen', 'Dining/Shop/Canteen')], default='provost_body', max_length=100)),
                ('blood_group', models.CharField(max_length=10)),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('registration_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.application')),
                ('password', models.CharField(max_length=100)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.hall')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.room')),
            ],
        ),
    ]
