# Generated by Django 5.2.1 on 2025-05-29 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dining_Shop_Canteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Official Email')),
                ('name', models.CharField(max_length=100)),
                ('official_role', models.CharField(choices=[('assistant_register', 'Assistant Register'), ('administrative_officer', 'Administrative Officer'), ('accountant', 'Accountant'), ('cleaner', 'Cleaner'), ('electrician', 'Electrician'), ('plumber', 'Plumber'), ('swiper', 'Swiper'), ('gardener', 'Gardener'), ('office_assistant', 'Office Assistant'), ('office_attendant', 'Office Attendant'), ('guard', 'Guard'), ('senior_assistant', 'Senior Assistant'), ('dining_shopping_canteen', 'Dining/Shopping/Canteen')], default='Electrician', max_length=100)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.hall')),
            ],
        ),
    ]
