# Generated by Django 5.2.1 on 2025-06-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addoffice',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A positive (A+)'), ('A-', 'A negative (A-)'), ('B+', 'B positive (B+)'), ('B-', 'B negative (B-)'), ('AB+', 'AB positive (AB+)'), ('AB-', 'AB negative (AB-)'), ('O+', 'O positive (O+)'), ('O-', 'O negative (O-)'), ('Others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A positive (A+)'), ('A-', 'A negative (A-)'), ('B+', 'B positive (B+)'), ('B-', 'B negative (B-)'), ('AB+', 'AB positive (AB+)'), ('AB-', 'AB negative (AB-)'), ('O+', 'O positive (O+)'), ('O-', 'O negative (O-)'), ('Others', 'Others')], max_length=100),
        ),
    ]
