# Generated by Django 5.2.1 on 2025-05-29 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addoffice',
            name='official_role',
            field=models.CharField(blank=True, choices=[('assistant_register', 'Assistant Register'), ('administrative_officer', 'Administrative Officer'), ('accountant', 'Accountant'), ('cleaner', 'Cleaner'), ('electrician', 'Electrician'), ('plumber', 'Plumber'), ('swiper', 'Swiper'), ('gardener', 'Gardener'), ('office_assistant', 'Office Assistant'), ('office_attendant', 'Office Attendant'), ('guard', 'Guard'), ('senior_assistant', 'Senior Assistant'), ('dining', 'Dining'), ('shop', 'Shop'), ('canteen', 'Canteen'), ('others', 'Others')], default='Assistant Register', help_text='Only for Official Person', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addoffice',
            name='user_role',
            field=models.CharField(choices=[('student', 'Student'), ('provost_body', 'Provost Body'), ('official_person', 'Official Person'), ('dining_shop_canteen', 'Dining/Shop/Canteen')], max_length=100),
        ),
        migrations.AlterField(
            model_name='officialperson',
            name='official_role',
            field=models.CharField(choices=[('assistant_register', 'Assistant Register'), ('administrative_officer', 'Administrative Officer'), ('accountant', 'Accountant'), ('cleaner', 'Cleaner'), ('electrician', 'Electrician'), ('plumber', 'Plumber'), ('swiper', 'Swiper'), ('gardener', 'Gardener'), ('office_assistant', 'Office Assistant'), ('office_attendant', 'Office Attendant'), ('guard', 'Guard'), ('senior_assistant', 'Senior Assistant'), ('dining', 'Dining'), ('shop', 'Shop'), ('canteen', 'Canteen'), ('others', 'Others')], default='Electrician', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='user_role',
            field=models.CharField(choices=[('student', 'Student'), ('provost_body', 'Provost Body'), ('official_person', 'Official Person'), ('dining_shop_canteen', 'Dining/Shop/Canteen')], default='provost_body', max_length=100),
        ),
        migrations.CreateModel(
            name='Dining_Shop_Canteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Official Email')),
                ('name', models.CharField(max_length=100)),
                ('official_role', models.CharField(choices=[('assistant_register', 'Assistant Register'), ('administrative_officer', 'Administrative Officer'), ('accountant', 'Accountant'), ('cleaner', 'Cleaner'), ('electrician', 'Electrician'), ('plumber', 'Plumber'), ('swiper', 'Swiper'), ('gardener', 'Gardener'), ('office_assistant', 'Office Assistant'), ('office_attendant', 'Office Attendant'), ('guard', 'Guard'), ('senior_assistant', 'Senior Assistant'), ('dining', 'Dining'), ('shop', 'Shop'), ('canteen', 'Canteen'), ('others', 'Others')], default='Electrician', max_length=100)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.hall')),
            ],
        ),
    ]
