# Generated by Django 5.2.1 on 2025-05-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addoffice',
            name='department_role',
            field=models.CharField(blank=True, choices=[('professor', 'Professor'), ('associate_professor', 'Associate Professor'), ('assistant_professor', 'Assistant Professor'), ('lecturer', 'Lecturer')], help_text='Only for Provost Body', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addoffice',
            name='official_role',
            field=models.CharField(blank=True, choices=[('assistant_register', 'Assistant Register'), ('administrative_officer', 'Administrative Officer'), ('accountant', 'Accountant'), ('cleaner', 'Cleaner'), ('electrician', 'Electrician'), ('plumber', 'Plumber'), ('swiper', 'Swiper'), ('gardener', 'Gardener'), ('office_assistant', 'Office Assistant'), ('office_attendant', 'Office Attendant'), ('guard', 'Guard'), ('senior_assistant', 'Senior Assistant'), ('dining_shopping_canteen', 'Dining/Shopping/Canteen')], default='Assistant Register', help_text='Only for Official Person', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addoffice',
            name='provost_body_role',
            field=models.CharField(blank=True, choices=[('provost', 'Provost'), ('assistant_provost', 'Assistant Provost')], help_text='Only for Provost Body', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addoffice',
            name='user_role',
            field=models.CharField(choices=[('student', 'Student'), ('provost_body', 'Provost Body'), ('official_person', 'Official Person'), ('dining', 'Dining'), ('canteen', 'Canteen'), ('shop', 'Shop')], default='Provost_Body', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='semester',
            field=models.CharField(choices=[('1/1', '1/1'), ('1/2', '1/2'), ('2/1', '2/1'), ('2/2', '2/2'), ('3/1', '3/1'), ('3/2', '3/2'), ('4/1', '4/1'), ('4/2', '4/2'), ('m/1', 'M/1'), ('m/2', 'M/2'), ('m/3', 'M/3')], max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='study_program',
            field=models.CharField(choices=[('undergraduate', 'UnderGraduate'), ('graduate', 'Graduate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='officialperson',
            name='official_role',
            field=models.CharField(choices=[('assistant_register', 'Assistant Register'), ('administrative_officer', 'Administrative Officer'), ('accountant', 'Accountant'), ('cleaner', 'Cleaner'), ('electrician', 'Electrician'), ('plumber', 'Plumber'), ('swiper', 'Swiper'), ('gardener', 'Gardener'), ('office_assistant', 'Office Assistant'), ('office_attendant', 'Office Attendant'), ('guard', 'Guard'), ('senior_assistant', 'Senior Assistant'), ('dining_shopping_canteen', 'Dining/Shopping/Canteen')], default='Electrician', max_length=100),
        ),
        migrations.AlterField(
            model_name='provostbody',
            name='department_role',
            field=models.CharField(choices=[('professor', 'Professor'), ('associate_professor', 'Associate Professor'), ('assistant_professor', 'Assistant Professor'), ('lecturer', 'Lecturer')], default='Professor', max_length=100),
        ),
        migrations.AlterField(
            model_name='provostbody',
            name='provost_body_role',
            field=models.CharField(choices=[('provost', 'Provost'), ('assistant_provost', 'Assistant Provost')], default='Provost', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='user_role',
            field=models.CharField(choices=[('student', 'Student'), ('provost_body', 'Provost Body'), ('official_person', 'Official Person'), ('dining', 'Dining'), ('canteen', 'Canteen'), ('shop', 'Shop')], default='Student', max_length=100),
        ),
    ]
