# Generated by Django 5.2.1 on 2025-05-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_addoffice_department_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='user_role',
            field=models.CharField(choices=[('student', 'Student'), ('provost_body', 'Provost Body'), ('official_person', 'Official Person'), ('dining', 'Dining'), ('canteen', 'Canteen'), ('shop', 'Shop')], default='Provost_body', max_length=100),
        ),
    ]
