# Generated by Django 5.2.1 on 2025-06-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_addoffice_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addoffice',
            name='password',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
