# Generated by Django 5.2.1 on 2025-05-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_userinformation_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addoffice',
            name='user_role',
            field=models.CharField(choices=[('student', 'Student'), ('provost_body', 'Provost Body'), ('official_person', 'Official Person'), ('dining', 'Dining'), ('canteen', 'Canteen'), ('shop', 'Shop')], default='provost_Body', max_length=100),
        ),
    ]
