# Generated by Django 5.2.1 on 2025-05-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_addoffice_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provostbody',
            name='provost_body_role',
            field=models.CharField(choices=[('provost', 'Provost'), ('assistant_provost', 'Assistant Provost')], default='provost', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='user_role',
            field=models.CharField(choices=[('student', 'Student'), ('provost_body', 'Provost Body'), ('official_person', 'Official Person'), ('dining', 'Dining'), ('canteen', 'Canteen'), ('shop', 'Shop')], default='provost_body', max_length=100),
        ),
    ]
