# Generated by Django 5.2.1 on 2025-05-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addoffice',
            name='user_role',
            field=models.CharField(choices=[('student', 'Student'), ('provost_body', 'Provost Body'), ('official_person', 'Official Person')], default='provost_body', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='user_role',
            field=models.CharField(choices=[('student', 'Student'), ('provost_body', 'Provost Body'), ('official_person', 'Official Person')], default='provost_body', max_length=100),
        ),
    ]
