# Generated by Django 5.2.1 on 2025-05-20 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_addoffice_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addoffice',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.hall'),
        ),
        migrations.AlterField(
            model_name='addoffice',
            name='user_role',
            field=models.CharField(choices=[('student', 'Student'), ('provost_body', 'Provost Body'), ('official_person', 'Official Person')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='blood_group',
            field=models.CharField(max_length=10),
        ),
    ]
