# Generated by Django 5.2.1 on 2025-05-20 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_alter_addoffice_hall_alter_addoffice_user_role_and_more'),
        ('registration', '0009_officialperson_hall_provostbody_hall_student_hall_and_more'),
    ]

    operations = [
    ]
