# Generated by Django 5.2.1 on 2025-05-20 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_officialperson_hall_provostbody_hall_student_hall_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialperson',
            name='hall',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='registration.hall'),
        ),
        migrations.AlterField(
            model_name='provostbody',
            name='hall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.hall'),
            preserve_default=False,
        ),
    ]
