# Generated by Django 5.2.1 on 2025-05-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_alter_officialperson_hall_alter_provostbody_hall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='premanent_address',
            new_name='permanent_address',
        ),
    ]
