# Generated by Django 5.2.1 on 2025-05-20 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_alter_officialperson_hall_alter_provostbody_hall'),
        ('registration', '0010_merge_20250520_0745'),
    ]

    operations = [
    ]
