# Generated by Django 5.2.1 on 2025-05-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_merge_20250520_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='premanent_address',
            new_name='permanent_address',
        ),
    ]
