# Generated by Django 5.2.1 on 2025-05-20 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0009_officialperson_hall_provostbody_hall_student_hall_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateMeeting',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting_date_time', models.DateTimeField(unique=True)),
                ('meeting_members', models.TextField(blank=True, null=True)),
                ('meeting_description', models.TextField()),
                ('meeting_topic', models.JSONField(blank=True, default=list)),
                ('meeting_decision', models.TextField(blank=True, null=True)),
                ('meeting_minutes', models.TextField(blank=True, null=True)),
                ('next_meeting_date_time', models.DateTimeField(blank=True, null=True)),
                ('meeting_chairperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaired_meetings', to='registration.provostbody')),
            ],
        ),
        migrations.CreateModel(
            name='AddTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_text', models.CharField(max_length=255)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_topics', to='meetings.createmeeting')),
            ],
        ),
    ]
