# Generated by Django 5.2.1 on 2025-05-22 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestRegistration',
            fields=[
                ('guest_id', models.AutoField(primary_key=True, serialize=False)),
                ('guest_name', models.CharField(max_length=100)),
                ('entry_date_time', models.DateTimeField()),
                ('exit_date_time', models.DateTimeField(blank=True, null=True)),
                ('guard_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests_registered', to='registration.officialperson')),
                ('reference_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests_referenced', to='registration.userinformation')),
            ],
            options={
                'ordering': ['-entry_date_time'],
            },
        ),
    ]
