# Generated by Django 5.2.1 on 2025-06-03 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_registration', '0001_initial'),
        ('registration', '0003_alter_addoffice_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuestRegistration',
            new_name='Guest',
        ),
    ]
