# Generated by Django 5.2.1 on 2025-05-19 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_registration', '0001_initial'),
        ('registration', '0008_alter_addoffice_user_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestregistration',
            options={'ordering': ['-entry_date_time']},
        ),
        migrations.AlterField(
            model_name='guestregistration',
            name='guard_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests_registered', to='registration.officialperson'),
        ),
    ]
