# Generated by Django 5.2.1 on 2025-05-19 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_registration', '0002_alter_guestregistration_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestregistration',
            options={'ordering': ['entry_date_time']},
        ),
    ]
