# Generated by Django 5.2.1 on 2025-05-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_registration', '0003_alter_guestregistration_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestregistration',
            options={'ordering': ['-entry_date_time']},
        ),
    ]
