# Generated by Django 5.2.1 on 2025-06-06 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('official', '0001_initial'),
        ('student_admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsEquipment',
            fields=[
                ('serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('equipment_name_and_number', models.TextField()),
                ('checked_out_time', models.DateTimeField()),
                ('checked_in_time', models.DateTimeField(blank=True, null=True)),
                ('guard_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_registered', to='official.officialperson')),
                ('reference_registration_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_checked_out', to='student_admission.student')),
            ],
            options={
                'ordering': ['-checked_out_time'],
            },
        ),
    ]
