# Generated by Django 5.2.1 on 2025-05-19 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_addoffice_user_role_and_more'),
        ('sport_equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsequipment',
            name='guard_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_registered', to='registration.userinformation'),
        ),
    ]
