# Generated by Django 5.2.1 on 2025-05-19 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_officialperson_hall_provostbody_hall_student_hall_and_more'),
        ('sport_equipment', '0002_alter_sportsequipment_guard_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsequipment',
            name='equipment_name_and_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sportsequipment',
            name='guard_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_registered', to='registration.officialperson'),
        ),
    ]
