# Generated by Django 5.2.1 on 2025-05-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_equipment', '0002_alter_sportsequipment_guard_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsequipment',
            name='equipment_name_and_number',
            field=models.TextField(),
        ),
    ]
