# Generated by Django 5.2.1 on 2025-05-20 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport_equipment', '0003_alter_sportsequipment_equipment_name_and_number'),
        ('sport_equipment', '0003_alter_sportsequipment_equipment_name_and_number_and_more'),
    ]

    operations = [
    ]
