# Generated by Django 5.2.1 on 2025-05-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport_equipment', '0003_alter_sportsequipment_equipment_name_and_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportsequipment',
            old_name='guard_email',
            new_name='guard',
        ),
    ]
