# Generated by Django 5.2.1 on 2025-05-10 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('hall_id', models.AutoField(primary_key=True, serialize=False)),
                ('hall_name', models.CharField(max_length=100)),
                ('total_room', models.PositiveIntegerField()),
                ('total_number_of_seat', models.PositiveIntegerField()),
                ('admitted_students', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='hall_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(default='default_name', max_length=255)),
                ('study_program', models.CharField(default='default_program', max_length=100)),
                ('cgpa', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('registration_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('blood_group', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('department_code', models.CharField(max_length=10)),
                ('study_program', models.CharField(choices=[('honors', 'Honors'), ('masters', 'Masters')], max_length=10)),
                ('session', models.CharField(choices=[('2019', '2019-2020'), ('2020', '2020-2021'), ('2021', '2021-2022'), ('2023', '2023-2024'), ('2024', '2024-2025')], max_length=10)),
                ('semester', models.CharField(choices=[('1/1', '1/1'), ('1/2', '1/2'), ('2/1', '2/1'), ('2/2', '2/2'), ('3/1', '3/1'), ('3/2', '3/2'), ('4/1', '4/1'), ('M/1', 'M/1'), ('M/2', 'M/2'), ('M/3', 'M/3')], max_length=20)),
                ('premanent_address', models.TextField()),
                ('home_distance_from_SUST_in_km', models.FloatField()),
                ('monthly_income', models.PositiveIntegerField()),
                ('special_reason_for_hall_seat', models.TextField(blank=True, null=True)),
                ('total_credits_offered', models.FloatField()),
                ('total_credits_completed', models.FloatField()),
                ('cgpa', models.FloatField()),
                ('last_semester_gpa', models.FloatField()),
                ('is_resident', models.BooleanField()),
                ('resident_months_in_university_hall', models.PositiveIntegerField(blank=True, null=True)),
                ('convicted', models.BooleanField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='student_profile_pictures/')),
                ('attached_hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admission.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=10)),
                ('capacity', models.PositiveIntegerField()),
                ('admitted_students', models.PositiveIntegerField(default=0)),
                ('student_list', models.JSONField(blank=True, default=list)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='admission.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.hall')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.room')),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(default='student', max_length=20)),
                ('blood_group', models.CharField(max_length=5)),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admission.hall')),
            ],
        ),
    ]
