# Generated by Django 5.2.1 on 2025-05-09 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('registration_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('blood_group', models.CharField(max_length=3)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('department_code', models.CharField(max_length=10)),
                ('study_program', models.CharField(choices=[('honors', 'Honors'), ('masters', 'Masters')], max_length=10)),
                ('session', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=20)),
                ('present_address', models.TextField()),
                ('distance_from_sust_km', models.FloatField()),
                ('monthly_income', models.PositiveIntegerField()),
                ('special_reason', models.TextField(blank=True, null=True)),
                ('total_credits_offered', models.FloatField()),
                ('total_credits_completed', models.FloatField()),
                ('cgpa', models.FloatField()),
                ('last_semester_gpa', models.FloatField()),
                ('is_resident', models.BooleanField()),
                ('resident_months', models.PositiveIntegerField(blank=True, null=True)),
                ('hall_preference', models.CharField(help_text="Enter like 'b a c'", max_length=5)),
                ('convicted', models.BooleanField(help_text='Have you ever been convicted for violation of any rule?')),
                ('attached_hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admission.hall')),
            ],
        ),
    ]
