# Generated by Django 5.2.1 on 2025-05-11 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='study_program',
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default='Default Department', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='room_number',
            field=models.CharField(default='default@example.com', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(default='default@example.com', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinformation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='admission',
            name='registration_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='admission.application'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
