# Generated by Django 5.2.1 on 2025-05-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_remove_admission_id_remove_student_cgpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='registration_number_str',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True),
        ),
    ]
