# Generated by Django 5.2.1 on 2025-05-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='blood_group',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='semester',
            field=models.CharField(choices=[('1/1', '1/1'), ('1/2', '1/2'), ('2/1', '2/1'), ('2/2', '2/2'), ('3/1', '3/1'), ('3/2', '3/2'), ('4/1', '4/1'), ('M/1', 'M/1'), ('M/2', 'M/2'), ('M/3', 'M/3')], max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='session',
            field=models.CharField(choices=[('2019-2020', 2019), ('2020-2021', 2020), ('2021-2022', 2021), ('2023-2024', 2023), ('2024-2025', 2024)], max_length=10),
        ),
    ]
