# Generated by Django 5.2.1 on 2025-05-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_alter_application_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='distance_from_sust_km',
            field=models.FloatField(verbose_name='SUST Distance (in Km)'),
        ),
    ]
