# Generated by Django 5.2.1 on 2025-05-09 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_alter_application_distance_from_sust_km'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='special_reason',
            new_name='special_reason_for_hall_seat',
        ),
        migrations.RemoveField(
            model_name='application',
            name='hall_preference',
        ),
    ]
