# Generated by Django 5.2.1 on 2025-06-06 16:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('official', '0001_initial'),
        ('student_admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meal_time', models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='breakfast', max_length=20, null=True)),
                ('item', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='official.dining_shop_canteen')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(help_text='Rating within 1-5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='dining_canteen_shop.additem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_admission.student')),
            ],
        ),
        migrations.CreateModel(
            name='HallOutlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_start', models.TimeField(blank=True, null=True)),
                ('breakfast_end', models.TimeField(blank=True, null=True)),
                ('lunch_start', models.TimeField(blank=True, null=True)),
                ('lunch_end', models.TimeField(blank=True, null=True)),
                ('dinner_start', models.TimeField(blank=True, null=True)),
                ('dinner_end', models.TimeField(blank=True, null=True)),
                ('shop_open_time', models.TimeField(blank=True, null=True)),
                ('shop_close_time', models.TimeField(blank=True, null=True)),
                ('rating', models.JSONField(blank=True, default=dict, null=True)),
                ('feedback', models.JSONField(blank=True, default=dict, null=True)),
                ('shop_items', models.JSONField(blank=True, null=True)),
                ('breakfast_items', models.JSONField(blank=True, null=True)),
                ('lunch_items', models.JSONField(blank=True, null=True)),
                ('dinner_items', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='official.dining_shop_canteen')),
            ],
        ),
    ]
