# Generated by Django 5.2.1 on 2025-05-22 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateOfficialTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date_time', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(max_length=255)),
                ('transaction_description', models.TextField()),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_file', models.JSONField(blank=True, default=list, null=True)),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='registration.officialperson')),
            ],
            options={
                'ordering': ['-transaction_date_time'],
            },
        ),
        migrations.CreateModel(
            name='AddFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='transactions/')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='official_transaction.createofficialtransaction')),
            ],
        ),
    ]
