# Generated by Django 5.2.1 on 2025-06-06 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Forum_Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_date_time', models.DateTimeField(auto_now_add=True)),
                ('text_message', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='forum/')),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to='user_info.userinformation')),
            ],
        ),
    ]
