# Generated by Django 5.2.1 on 2025-05-20 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0011_merge_20250520_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_date_time', models.DateTimeField(auto_now_add=True)),
                ('text_message', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='forum/')),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to='registration.userinformation')),
            ],
        ),
    ]
