# Generated by Django 5.2.1 on 2025-06-03 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        ('registration', '0003_alter_addoffice_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forum',
            new_name='New_Forum_Post',
        ),
    ]
