# Generated by Django 5.2.1 on 2025-05-30 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_complaints_received', models.PositiveBigIntegerField(default=0)),
                ('total_complaints_resolved', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('complain_id', models.AutoField(primary_key=True, serialize=False)),
                ('complain_date', models.DateField(auto_now_add=True)),
                ('complain_tag', models.CharField(choices=[('water_supply', 'Water Supply'), ('room_clean', 'Room Clean'), ('toilet_clean', 'Toilet Clean'), ('bathroom', 'Bathroom'), ('electric', 'Electric'), ('dining', 'Dining'), ('shop', 'Shop'), ('canteen', 'Canteen'), ('wi_fi', 'Wi-Fi'), ('reading_room', 'Reading Room'), ('drainage_system', 'Drainage System'), ('bed', 'Bed'), ('locker', 'Locker'), ('window_glass', 'Window Glass'), ('mosquito_net_stand', 'Mosquito Net Stand'), ('administrative', 'Administrative'), ('others', 'Others')], max_length=20)),
                ('complain_details', models.CharField(max_length=1000)),
                ('complain_status', models.CharField(choices=[('received', 'Received'), ('in_process', 'In Process'), ('resolved', 'Resolved')], default='Received', max_length=20)),
                ('complainant_registration_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.student')),
            ],
        ),
    ]
