# Generated by Django 5.2.1 on 2025-05-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='id',
        ),
        migrations.AddField(
            model_name='complain',
            name='complain_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
