# Generated by Django 5.2.1 on 2025-06-03 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0001_initial'),
        ('registration', '0003_alter_addoffice_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complain',
            new_name='Make_Complaints',
        ),
    ]
