# Generated by Django 5.2.1 on 2025-05-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0002_remove_complain_id_complain_complain_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='complainant_name',
        ),
    ]
