# Generated by Django 5.2.1 on 2025-06-06 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halls_and_rooms', '0001_initial'),
        ('official', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddOffice',
            new_name='OfficialRegistration',
        ),
    ]
