# Generated by Django 5.2.1 on 2025-06-13 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0003_alter_officialregistration_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialregistration',
            name='phone_number',
            field=models.CharField(help_text='Enter 11-digit local or 14-digit international format (e.g., 01XXXXXXXXX or +8801XXXXXXXXX)', max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format '+8801XXXXXXXXX' or '01XXXXXXXXX'.", regex='^(\\+8801[3-9]\\d{8}|01[3-9]\\d{8})$')]),
        ),
    ]
