# Generated by Django 5.2.1 on 2025-05-20 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0010_merge_20250520_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False)),
                ('notice_data_and_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('notice_sender_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='registration.provostbody')),
            ],
        ),
    ]
