# Generated by Django 5.2.1 on 2025-06-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0001_initial'),
        ('official', '0004_alter_officialregistration_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoticeBoard',
            new_name='Notices',
        ),
    ]
