# Generated by Django 5.2.1 on 2025-05-22 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostAndFound',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_date_time', models.DateTimeField(auto_now_add=True)),
                ('element_name', models.CharField(max_length=255)),
                ('element_description', models.TextField()),
                ('found_location', models.TextField()),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_and_found/')),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_and_found_posts', to='registration.userinformation')),
            ],
            options={
                'ordering': ['-post_date_time'],
            },
        ),
    ]
