# Generated by Django 5.2.1 on 2025-06-03 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost_and_found', '0001_initial'),
        ('registration', '0003_alter_addoffice_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LostAndFound',
            new_name='New_LostAndFound',
        ),
    ]
