# Generated by Django 5.2.1 on 2025-06-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_and_found', '0002_new_lostandfound_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_lostandfound',
            name='found_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
