# Generated by Django 5.2.1 on 2025-06-06 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('halls_and_rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('registration_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A positive (A+)'), ('A-', 'A negative (A-)'), ('B+', 'B positive (B+)'), ('B-', 'B negative (B-)'), ('AB+', 'AB positive (AB+)'), ('AB-', 'AB negative (AB-)'), ('O+', 'O positive (O+)'), ('O-', 'O negative (O-)'), ('Others', 'Others')], max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('department_name', models.CharField(max_length=100)),
                ('study_program', models.CharField(choices=[('undergraduate', 'UnderGraduate'), ('graduate', 'Graduate')], max_length=20)),
                ('session', models.CharField(choices=[('2019', '2019-2020'), ('2020', '2020-2021'), ('2021', '2021-2022'), ('2022', '2022-2023'), ('2023', '2023-2024'), ('2024', '2024-2025')], max_length=10)),
                ('semester', models.CharField(choices=[('1/1', '1/1'), ('1/2', '1/2'), ('2/1', '2/1'), ('2/2', '2/2'), ('3/1', '3/1'), ('3/2', '3/2'), ('4/1', '4/1'), ('4/2', '4/2'), ('m/1', 'M/1'), ('m/2', 'M/2'), ('m/3', 'M/3')], max_length=20)),
                ('permanent_address', models.TextField()),
                ('home_distance_from_SUST_in_km', models.FloatField()),
                ('family_monthly_income', models.PositiveIntegerField()),
                ('special_reason_for_hall_seat', models.TextField(blank=True, null=True)),
                ('total_credits_offered', models.FloatField()),
                ('total_credits_completed', models.FloatField()),
                ('cgpa', models.FloatField()),
                ('last_semester_gpa', models.FloatField()),
                ('is_resident', models.BooleanField()),
                ('resident_months_in_university_hall', models.PositiveIntegerField(blank=True, null=True)),
                ('convicted', models.BooleanField(help_text='Have ever been penalized by university authority?')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='student_profile_pictures/')),
                ('attached_hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='halls_and_rooms.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(default='', max_length=100)),
                ('department', models.CharField(default='', max_length=100)),
                ('semester', models.CharField(max_length=20)),
                ('session', models.CharField(max_length=10)),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='halls_and_rooms.hall')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='halls_and_rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('registration_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student_admission.application')),
                ('password', models.CharField(editable=False, max_length=100)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halls_and_rooms.hall')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halls_and_rooms.room')),
            ],
        ),
    ]
