# Generated by Django 5.2.1 on 2025-06-07 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(help_text='Enter 11-digit local or 14-digit international format (e.g., 018XXXXXXXX or +88018XXXXXXXX)', max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format '+8801XXXXXXXXX' or '01XXXXXXXXX'.", regex='^(\\+8801[3-9]\\d{8}|01[3-9]\\d{8})$')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='registration_number',
            field=models.CharField(help_text='Must be exactly 10 digits (e.g., 2020331007)', max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Registration number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
