# Generated by Django 5.2.1 on 2025-06-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls_and_rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='hall_name',
            field=models.CharField(help_text='Unique name for the hall', max_length=100, unique=True),
        ),
    ]
