# Generated by Django 5.2.1 on 2025-06-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls_and_rooms', '0002_alter_hall_hall_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='block',
            field=models.CharField(choices=[('A', 'Block A'), ('B', 'Block B'), ('C', 'Block C'), ('D', 'Block D')], default='A', max_length=100),
        ),
    ]
