# Generated by Django 5.2.1 on 2025-06-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls_and_rooms', '0003_room_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='block',
            field=models.CharField(choices=[('A', 'Block A'), ('B', 'Block B'), ('C', 'Block C'), ('D', 'Block D'), ('None', 'None')], default='A', max_length=100),
        ),
    ]
